// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'IconCarbon:arrowRight': typeof import('~icons/carbon/arrow-right')['default']
    'IconCarbon:chevronLeft': typeof import('~icons/carbon/chevron-left')['default']
    'IconCarbon:logoGithub': typeof import('~icons/carbon/logo-github')['default']
    'IconCarbon:moon': typeof import('~icons/carbon/moon')['default']
    'IconCarbon:sun': typeof import('~icons/carbon/sun')['default']
    'IconCarbon:trashCan': typeof import('~icons/carbon/trash-can')['default']
    Starport: typeof import('vue-starport')['Starport']
    StarportCarrier: typeof import('vue-starport')['StarportCarrier']
  }
}

export {}
